### ISSUE TITLE
repair_max_slew causes segmentation fault on some designs

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/Resizer#10]
**Priority:** Medium

**Tool:** Resizer

**Version:** 98568f2713

**Issue:** 
For certain large desigs, the resize commands throws a segmentation fault only when repair_max_slew is enabled. It is possible that this may be an issue related to builds and runs in CentOS 6 environments (vs CentOS 7)

**Steps to reproduce:** 
The issue currently only reproduced on tsmc65lp designs. The testcase will be sent privately. You can use this docker file at https://github.com/The-OpenROAD-Project/alpha-release/blob/master/build/docker/resizer/Dockerfile to build and test resizer on CentOS6

**Comment by jjcherry56** [comment]
ebb043e Sat Aug 10 21:48:11 2019 -0700 buffer insertion seg fault on floating nets
