### ISSUE TITLE
"by" in ROW definition not accepted by ioPlacer

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/Resizer#14]
Hello,

verilog2def generates ROW statements with `by` lower case. (i.e. `ROW rowName siteName origX origY siteOrient DO numX by numY STEP stepX stepY`). Which are not accepted by an updated ioPlacer. A fix would be to capitalize `by`.

**Comment by jjcherry56** [comment]
verilog2def is no longer supported
see the initilize_floorplan command in the OpenROAD tool
