### ISSUE TITLE
Please clarify build requirements

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/Resizer#2]
Can you please clarify the build requirements?
opensta, lef, def and flute were listed as requirements (in a sister level folder) but the instructions are not clear where to get them from (and which version to use). Also that the components need to be built before hand.

I have tried the versions of lef/def in the latest version of replace, but the cmake of resizer appears to be looking for object files at a different level. The versions of lef/def from si2 appear to have a build issue with semi-colons in lef.y

Thanks

**Comment by jjcherry56** [comment]
The resizer isn't really set up for general consumption at this point.
I had no idea anyone was trying to actually use it.
I am hoping Tom Spyrou and bring sanity to the chaos in the OR software build world.

**Comment by tajayi** [comment]
Thanks. I am hoping so as well. I was able to navigate my way around to figure out the right recipe to get this working. For reference, I am building this (and other OR tools) in docker images. The dockerfile for resizer is here: https://github.com/The-OpenROAD-Project/release/blob/master/build/docker/resizer/Dockerfile

I'll go ahead and close this issue since it's part of a larger effort that needs to be addressed

**Comment by jjcherry56** [comment]
I spent yesterday and today cleaning up the build.
It should be straightforward now. See README.md

**Comment by tajayi** [comment]
Thanks. I'll pull this in my new builds
