### ISSUE TITLE
Segmentation fault on Coyote testcase

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/Resizer#3]
I am currently experiencing a segmentation fault on the coyote testcase.

Logs/scripts and everything required to reproduce the crash is in t8_resizer_2019-06-23_13-06.tar.gz

(I have sent @jjcherry56 an invite to the gdrive with the attachments)

using build from commit 5cc916d4fab1635b08c2328a37b6a050a7d239eb

**Comment by jjcherry56** [comment]
There were some absolute paths in libFilePaths.txt but I found the
libraries in another incarnation of the
wiley coyote.

I pushed a fix for this (the flute package blew out the stack working on
the clock net).

I just added a -dont_use option to resize. I suggest using
   resize -dont_use */DLY*
to avoid DLY cells, which functionally look like buffers but have large
intrinsic delay.

The resizer is still in pretty rough shape. There are a number of problems
I am trying to sort
through and it is nowhere close to stable yet. Just keep that in mind when
you are using it.
You can see the results aren't very good on this design, and I have been
aware of that for a while
now. It is just taking some time to work through the kinks of the real
world.

**Comment by tajayi** [comment]
Thanks @jjcherry56. I'll rebuild and give it a try.
