### ISSUE TITLE
Verilog2def generates VERSION 5.5 defs

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/Resizer#6]
**Priority:** Low

**Tool:** verilog2def

**Version:** commit 98568f2713

**Issue:**
Verilog2def generates lefs with version 5.5. The downstream tools (specifcally pdn generator) requires lefs with 5.6 or higher to describe certain via generation rules. Currently working around that by using sed to change it after generation

**Steps to reproduce:**
Run verilog2def on any design

**Comment by jjcherry56** [comment]
changed it to write 5.7
