### ISSUE TITLE
Resizer does not properly parse split bus ports

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/Resizer#9]
**Priority:** Medium

**Tool:** Resizer

**Version:** 98568f2713

**Issue:**
Resizer does not properly handle designs with split bus ports on the toplevel. When the toplevel port has the syntax `\signal[0]` the connection printed after parsing is `\signal [0]`  (note the space) which will be unconnected

**Steps to reproduce:**
Run Resizer on the attached design. Notice that the connections between the toplevel port do not exist due to inconsistency in the signal name

[resizer_ports.tar.gz](https://github.com/The-OpenROAD-Project/Resizer/files/3489302/resizer_ports.tar.gz)

**Comment by jjcherry56** [comment]
02296d2 Tue Aug 13 21:35:20 2019 -0700 write_verilog escaped bus name
